"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Sign(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERID_FIELD_NUMBER: builtins.int
    SIGNTYPE_FIELD_NUMBER: builtins.int
    DATE_FIELD_NUMBER: builtins.int
    userid: builtins.int
    signtype: builtins.int
    date: builtins.str
    def __init__(
        self,
        *,
        userid: builtins.int = ...,
        signtype: builtins.int = ...,
        date: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["date", b"date", "signtype", b"signtype", "userid", b"userid"]) -> None: ...

global___Sign = Sign

@typing.final
class Mail(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    CONTEXT_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    ATTACH_FIELD_NUMBER: builtins.int
    BUTTONTEXT_FIELD_NUMBER: builtins.int
    FROMUSERID_FIELD_NUMBER: builtins.int
    ISGLOBAL_FIELD_NUMBER: builtins.int
    title: builtins.str
    context: builtins.str
    type: builtins.int
    attach: builtins.str
    buttontext: builtins.str
    fromuserid: builtins.int
    isglobal: builtins.int
    @property
    def userid(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        userid: collections.abc.Iterable[builtins.int] | None = ...,
        title: builtins.str = ...,
        context: builtins.str = ...,
        type: builtins.int = ...,
        attach: builtins.str = ...,
        buttontext: builtins.str = ...,
        fromuserid: builtins.int = ...,
        isglobal: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["attach", b"attach", "buttontext", b"buttontext", "context", b"context", "fromuserid", b"fromuserid", "isglobal", b"isglobal", "title", b"title", "type", b"type", "userid", b"userid"]) -> None: ...

global___Mail = Mail
