"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Message(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERID_FIELD_NUMBER: builtins.int
    MSGID_FIELD_NUMBER: builtins.int
    ACTIONTYPE_FIELD_NUMBER: builtins.int
    STRING_FIELD_NUMBER: builtins.int
    userid: builtins.int
    msgid: builtins.int
    actiontype: builtins.int
    string: builtins.bytes
    def __init__(
        self,
        *,
        userid: builtins.int = ...,
        msgid: builtins.int = ...,
        actiontype: builtins.int = ...,
        string: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["actiontype", b"actiontype", "msgid", b"msgid", "string", b"string", "userid", b"userid"]) -> None: ...

global___Message = Message
